{% set name = "pyobjc-framework-FSEvents" %}
{% set version = "8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8f0fef6d2c9bf21db1f81f0e4b96daf84d4d5375ebbee87ba7e72c5ec1e595ce

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [(not osx) or py2k]

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - pyobjc-core >=6.1
    - pyobjc-framework-cocoa >=6.1

test:
  imports:
    - FSEvents

about:
  home: https://bitbucket.org/ronaldoussoren/pyobjc
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Wrappers for the framework FSEvents on macOS

extra:
  recipe-maintainers:
    - xhochy
