{% set name = "pyobjc-framework-FSEvents" %}
{% set version = "12.1" %}
{% set pypi_name = name|replace("-", "_")|lower %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ pypi_name[0] }}/{{ name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: a22350e2aa789dec59b62da869c1b494a429f8c618854b1383d6473f4c065a02

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [not osx or py<310]

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - pyobjc-core >={{ version }}
    - pyobjc-framework-cocoa >={{ version }}

test:
  imports:
    - FSEvents
  requires:
    - pip
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"

about:
  home: https://github.com/ronaldoussoren/pyobjc
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Wrappers for the framework FSEvents on macOS
  description: |
    Wrappers for the framework FSEvents on macOS
  dev_url: https://github.com/ronaldoussoren/pyobjc/tree/master/pyobjc-framework-FSEvents
  doc_url: https://github.com/ronaldoussoren/pyobjc

extra:
  recipe-maintainers:
    - xhochy
