{% set name = "pyobjc-framework-FSEvents" %}
{% set version = "12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pyobjc-framework-FSEvents/pyobjc_framework_fsevents-12.0.tar.gz
  sha256: 768bfc90da3547516b6833e33f28d5f49238c2b47f44b8a9b7c941b951488cd9

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [(not osx) or py<39]

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - pyobjc-core >=12.0
    - pyobjc-framework-cocoa >=12.0

test:
  imports:
    - FSEvents
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/ronaldoussoren/pyobjc
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Wrappers for the framework FSEvents on macOS
  description: |
    Wrappers for the framework FSEvents on macOS
  dev_url: https://github.com/ronaldoussoren/pyobjc/tree/master/pyobjc-framework-FSEvents
  doc_url: https://github.com/ronaldoussoren/pyobjc

extra:
  recipe-maintainers:
    - xhochy
