{% set name = "pyobjc-framework-FSEvents" %}
{% set version = "6.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8e2cdfb48e1bca53dc67fc4b219a891ec6c07b2a422f7e3da0ce4ccff258f2b7

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [(not osx) or py2k]

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - pyobjc-core >={{ version }}
    - pyobjc-framework-cocoa >={{ version }}

test:
  imports:
    - FSEvents

about:
  home: https://bitbucket.org/ronaldoussoren/pyobjc
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Wrappers for the framework FSEvents on macOS

extra:
  recipe-maintainers:
    - xhochy
